### ISSUE TITLE
Problem when creating new BBS

### ISSUE THREAD

**Issue by ghost** [shingetsu-gou/shingetsu-gou#20]
Hello , I am having a problem when trying to create a new BBS:

seems the BBS is created having as a date 1970-01-01 , and there is no way to insert messages in it. 

When I click I get an "empty response". 

Is there something which I need to set in the config to have this function working?
All the remaining functionalities are ok...

My OS is Debian stable 8, I am compiling it with Golang 1.5 .

How to riproduce: download Gou, compile and start with the provided configuration. Then "create a new BBS".

thanks,

**Comment by utamaro** [comment]
Saku, python version of shinGETtu, displays new BBS as it was updated on 1970-01-01 if BBS has no messages. Gou doesn't display BBS itself.  
And messages in new BBS is initially hard to be spread because  shinGETsu tries to get messages in  BBS which the node has already read.
I think this feature is a weak point of shinGETsu protocol, but In shinGETsu thought, popular BBS shoudl be more spread, and not popular BBS, like spam, should not be spread.

Maybe I don't understand what you want to say by 
_there is no way to insert messages in it._
but,

if you make a new BBS and continuouly make a message, you can insert messages.
If you only make a new BBS and close the next page(i.e. you don't make a message),  you can make a BBS which has a same name and can make a massage.

**Comment by ghost** [comment]
```
Saku, python version of shinGETtu, displays new BBS as it was updated on 1970-01-01 
if BBS has no      messages. Gou doesn't display BBS itself.
```

Ok, this is not a big problem.

The problem is that clicking on the link of the newly created BBS, it answers with a "empty response" to the browser. So I can't add any initial message to the thread. 

```
if you make a new BBS and continuouly make a message on the next page, you can insert messages.
If you only make a new BBS and close the next page(i.e. you don't make a message), 
you can make a   BBS which has a same name once again then you can make a massage.
```

this is the part I don't get.When I create a new BBS, I have no "next page". 

Imagine I want to create a new BBS and then post the first message. What I am supposed to do exactly? 

What happens now is that I create a new BBS, and the server brings me to an empty error page. Then If I go back, i see the new bbs created between the "recent", but If I click on it I still see the empty page. Could you describe in detail how to add a new message in the newly created BBS? This would be helpful. Unfortunately I don't speak japanese, so I cant read manuals in japanese :(

**Comment by utamaro** [comment]
ok, this may be a bug in Gou.
I made a new BBS with screenshots, hoping it will be help to you.
 
![](http://i.imgur.com/NEWk2Zy.png)
![](http://imgur.com/gr6Ry7O.png)
![](http://imgur.com/qS6SXy6.png)
![](http://imgur.com/IY17Ese.jpg)

**Comment by ghost** [comment]
Hi. To me it works in a different way:

![screenshot - 101215 - 21 57 57](https://cloud.githubusercontent.com/assets/4519054/11728267/29f06818-9f89-11e5-9f70-1798d1d7e349.png)

![screenshot - 101215 - 21 58 46](https://cloud.githubusercontent.com/assets/4519054/11728281/411dbfcc-9f89-11e5-8fba-3f0ee1c28fbc.png)

And when I click...

![screenshot - 101215 - 21 59 16](https://cloud.githubusercontent.com/assets/4519054/11728296/56b85bda-9f89-11e5-988d-3a00c9fa7752.png)

Now, If I go on "INDEX" I can see the bbs was created....

![screenshot - 101215 - 22 00 02](https://cloud.githubusercontent.com/assets/4519054/11728321/77243f38-9f89-11e5-8003-872e2a601dad.png)

But then I don't know how to add a message. And, If I click to the newly created BBS, I get:

![screenshot - 101215 - 22 01 03](https://cloud.githubusercontent.com/assets/4519054/11728336/8fdc3986-9f89-11e5-8a90-5935b2493afc.png)

Which I cannot understand.

The relevant log follows. Also it complains because of no Asset file/message-en-US.txt, but I created one, and nothing changed.

# 

```
2015/11/27 20:46:36 node.go:379: Talk: http://rep4649.ddo.jp:8000/server.cgi/join/87.143.98.229:8000+server.cgi
```

2015/11/27 20:46:39 loggingServeMux.go:54: [::1]:44672 GET /thread.cgi/altPanzer Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36 http://localhost:8000/gateway.cgi/
2015/11/27 20:46:39 gateway.go:63: Asset file/message-en-US.txt not found
2015/11/27 20:46:39 node.go:379: Talk: http://24.130.242.114:8080/server.cgi/head/thread_616C7450616E7A6572/1445975199-
2015/11/27 20:46:39 server.go:1934: http: panic serving [::1]:44672: runtime error: invalid memory address or nil pointer dereference
goroutine 327 [running]:
net/http.(_conn).serve.func1(0xc82046efd0, 0x7f7ba3f78810, 0xc8202fab70)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1287 +0xb5
github.com/shingetsu-gou/shingetsu-gou/thread.(_Cache).waitFor(0xc820489450, 0xb98d01, 0xc820560c00, 0xc820471400)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/thread/cache.go:410 +0x7b
github.com/shingetsu-gou/shingetsu-gou/thread.(_Cache).GetCache(0xc820489450, 0xaad901, 0x0)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/thread/cache.go:402 +0x243
github.com/shingetsu-gou/shingetsu-gou/cgi.(_threadCGI).printThreadHead(0xc820e0d808, 0xc82048c390, 0x9, 0x0, 0x0, 0x0, 0xc820489450, 0xaf0ed0, 0x10, 0x0, ...)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/cgi/thread_cgi.go:275 +0x4be
github.com/shingetsu-gou/shingetsu-gou/cgi.(_threadCGI).printThread(0xc820e0d808, 0xc82048c390, 0x9, 0x0, 0x0, 0x0)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/cgi/thread_cgi.go:372 +0x17c
github.com/shingetsu-gou/shingetsu-gou/cgi.printThread(0x7f7ba3f78a40, 0xc82012dbf0, 0xc820443ea0)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/cgi/thread_cgi.go:117 +0x2aa
net/http.HandlerFunc.ServeHTTP(0xb98d60, 0x7f7ba3f78a40, 0xc82012dbf0, 0xc820443ea0)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc8204ba500, 0x7f7ba3f78a40, 0xc82012dbf0, 0xc820443ea0)
    /home/loweel/Documents/gitio/golib/src/github.com/gorilla/mux/mux.go:100 +0x29e
github.com/gorilla/handlers.CompressHandlerLevel.func1(0x7f7ba3f78a40, 0xc82012dbf0, 0xc820443ea0)
    /home/loweel/Documents/gitio/golib/src/github.com/gorilla/handlers/compress.go:102 +0x49b
net/http.HandlerFunc.ServeHTTP(0xc82030ed80, 0x7f7ba3f78990, 0xc8205d4000, 0xc820443ea0)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1422 +0x3a
net/http.(_ServeMux).ServeHTTP(0xc8203be9c0, 0x7f7ba3f78990, 0xc8205d4000, 0xc820443ea0)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1699 +0x17d
github.com/shingetsu-gou/shingetsu-gou/cgi.(_LoggingServeMux).ServeHTTP(0xc8203c6040, 0x7f7ba3f78990, 0xc8205d4000, 0xc820443ea0)
    /home/loweel/Documents/gitio/golib/src/github.com/shingetsu-gou/shingetsu-gou/cgi/loggingServeMux.go:55 +0x30a
net/http.serverHandler.ServeHTTP(0xc8203cc5a0, 0x7f7ba3f78990, 0xc8205d4000, 0xc820443ea0)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc82046efd0)
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1361 +0xbee
created by net/http.(_Server).Serve
    /home/loweel/Documents/gitio/go/src/net/http/server.go:1910 +0x3f6

**Comment by utamaro** [comment]
What version are you using?
At first do ```git pull ``` to ensure that you are using newest version :)
